# version: "3.8"
services:
  cdn:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: cdn_server
    ports:
      - "8000:8000"
    volumes:
      - ./go/server/content:/app/content
      - ./go/server/assets:/app/assets  # ✅ Correct path to content

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./config/default.conf:/etc/nginx/conf.d/default.conf  # ✅ Correct location
    depends_on:
      - cdn
